Learning Jenkins

diff --git a/ProvisonToJavaDeploy/Jenkinsfile b/ProvisonToJavaDeploy/Jenkinsfile
--- a/ProvisonToJavaDeploy/Jenkinsfile
+++ b/ProvisonToJavaDeploy/Jenkinsfile
@@ -90,13 +90,15 @@ pipeline {
                         sh """
                             docker save $IMAGE_NAME > app.tar
                             echo "Running SCP to EC2"
-                            scp -vvv -o StrictHostKeyChecking=no -i "$EC2_PEM" app.tar ubuntu@${ec2_ip}:/home/ubuntu/
+                            scp -o StrictHostKeyChecking=no -i "$EC2_PEM" app.tar ubuntu@${ec2_ip}:/home/ubuntu/
                         """
+
                         sh """
-                            echo "Running SSH to load and run Docker image"
+                            echo "Running SSH to load and run Docker container"
                             ssh -o StrictHostKeyChecking=no -i "$EC2_PEM" ubuntu@${ec2_ip} '
                                 docker load < /home/ubuntu/app.tar &&
-                                docker run --rm $IMAGE_NAME
+                                docker rm -f $IMAGE_NAME || true &&
+                                docker run -d --name $IMAGE_NAME $IMAGE_NAME
                             '
                         """
                     }
@@ -107,10 +109,10 @@ pipeline {
 
     post {
         success {
-            echo 'Deployment pipeline completed successfully.'
+            echo '✅ Deployment pipeline completed successfully.'
         }
         failure {
-            echo 'Deployment pipeline failed. Check logs above.'
+            echo '❌ Deployment pipeline failed. Check logs above.'
         }
     }
 }
